### ISSUE TITLE
p2pool crashed

### ISSUE THREAD

**Issue by mahrens917** [p2pool/p2pool#238]
This happened to at least one other p2pool at the around the same time.  Mine just crashed and the error is log is:

```
2014-12-01 11:18:02.588364 > Traceback (most recent call last):
2014-12-01 11:18:02.809783 >   File "/home/ubuntu/p2pool/p2pool/work.py", line 345, in got_response
2014-12-01 11:18:02.961591 >     helper.submit_block(dict(header=header, txs=[new_gentx] + other_transactions), False, self.node.factory, self.node.bitcoind, self.node.bitcoind_work, self.node.net)
2014-12-01 11:18:02.982222 >   File "/home/ubuntu/p2pool/p2pool/bitcoin/helper.py", line 86, in submit_block
2014-12-01 11:18:02.982273 >     submit_block_p2p(block, factory, net)
2014-12-01 11:18:02.982317 >   File "/usr/lib/pypy/dist-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
2014-12-01 11:18:02.982359 >     return _inlineCallbacks(None, gen, Deferred())
2014-12-01 11:18:02.982399 >   File "/usr/lib/pypy/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
2014-12-01 11:18:02.982441 >     result = g.send(result)
2014-12-01 11:18:02.982481 > --- <exception caught here> ---
2014-12-01 11:18:02.982521 >   File "/home/ubuntu/p2pool/p2pool/util/deferral.py", line 41, in f
2014-12-01 11:18:02.982560 >     result = yield func(*args, **kwargs)
2014-12-01 11:18:02.982598 >   File "/home/ubuntu/p2pool/p2pool/bitcoin/helper.py", line 67, in submit_block_p2p
2014-12-01 11:18:02.982637 >     factory.conn.value.send_block(block=block)
2014-12-01 11:18:02.982675 >   File "/home/ubuntu/p2pool/p2pool/util/p2protocol.py", line 102, in <lambda>
2014-12-01 11:18:02.983130 >     return lambda **payload2: self.sendPacket(command, payload2)
2014-12-01 11:18:02.983177 >   File "/home/ubuntu/p2pool/p2pool/util/p2protocol.py", line 93, in sendPacket
2014-12-01 11:18:02.983219 >     raise TooLong('payload too long')
2014-12-01 11:18:02.984567 > p2pool.util.p2protocol.TooLong: payload too long
```

**Comment by mahrens917** [comment]
I received this error twice more and did some digging.

The "payload too long" error comes about when a packet's length is greater than max_payload_length.  This can be seen in p2pool/util/p2protocol.py.

This is called from p2pool/bitcoin/p2p.py and p2pool/p2p.py where it sets max_payload_length to 1,000,000.

I am going to change the code to print out the packet size, as well as, change the max_payload_length to twice the size.  I will let the code run for awhile and see what happens and report back.

**Comment by farsider350** [comment]
Closing due to inactivity.
