### ISSUE TITLE
Strange Error after doing a clean clone of P2Pool

### ISSUE THREAD

**Issue by bolehvpn** [p2pool/p2pool#245]
Had a previously working p2pool but decided to try reinstalling it (smart idea). on Ubuntu 14.04 LTS

Now getting this error and not sure what's wrong

raceback (most recent call last):
2015-01-22 01:15:33.184179 >   File "/home/reuben/p2pool/p2pool/main.py", line 666, in run
2015-01-22 01:15:33.190837 >     reactor.run()
2015-01-22 01:15:33.190960 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 01:15:33.191029 >     self.mainLoop()
2015-01-22 01:15:33.191075 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 01:15:33.191120 >     self.runUntilCurrent()
2015-01-22 01:15:33.191161 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 01:15:33.191204 >     call.func(*call.args, **call.kw)
2015-01-22 01:15:33.191244 > --- <exception caught here> ---
2015-01-22 01:15:33.191336 >   File "/home/reuben/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 01:15:33.191387 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 01:15:33.191433 >   File "/home/reuben/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 01:15:33.191475 >     x, handler = self._inner.get_work(*args)
2015-01-22 01:15:33.191538 >   File "/home/reuben/p2pool/p2pool/work.py", line 243, in get_work
2015-01-22 01:15:33.191581 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 01:15:33.191623 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2015-01-22 01:15:33.273671 > Unhandled Error
2015-01-22 01:15:33.273834 > Traceback (most recent call last):
2015-01-22 01:15:33.273908 >   File "/home/reuben/p2pool/p2pool/main.py", line 666, in run
2015-01-22 01:15:33.274001 >     reactor.run()
2015-01-22 01:15:33.274065 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 01:15:33.274140 >     self.mainLoop()
2015-01-22 01:15:33.274231 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 01:15:33.274352 >     self.runUntilCurrent()
2015-01-22 01:15:33.274427 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 01:15:33.274495 >     call.func(*call.args, **call.kw)
2015-01-22 01:15:33.274551 > --- <exception caught here> ---
2015-01-22 01:15:33.274617 >   File "/home/reuben/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 01:15:33.274662 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 01:15:33.274707 >   File "/home/reuben/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 01:15:33.274767 >     x, handler = self._inner.get_work(*args)
2015-01-22 01:15:33.274809 >   File "/home/reuben/p2pool/p2pool/work.py", line 243, in get_work
2015-01-22 01:15:33.274869 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 01:15:33.274965 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2015-01-22 01:15:33.315493 > Unhandled Error
2015-01-22 01:15:33.315694 > Traceback (most recent call last):
2015-01-22 01:15:33.315772 >   File "/home/reuben/p2pool/p2pool/main.py", line 666, in run
2015-01-22 01:15:33.315822 >     reactor.run()
2015-01-22 01:15:33.315865 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 01:15:33.315923 >     self.mainLoop()
2015-01-22 01:15:33.315966 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 01:15:33.316010 >     self.runUntilCurrent()
2015-01-22 01:15:33.316051 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 01:15:33.316094 >     call.func(*call.args, **call.kw)
2015-01-22 01:15:33.316135 > --- <exception caught here> ---
2015-01-22 01:15:33.316175 >   File "/home/reuben/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 01:15:33.316217 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 01:15:33.316261 >   File "/home/reuben/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 01:15:33.316303 >     x, handler = self._inner.get_work(*args)
2015-01-22 01:15:33.316344 >   File "/home/reuben/p2pool/p2pool/work.py", line 243, in get_work
2015-01-22 01:15:33.316408 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 01:15:33.316463 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares

And this:

2015-01-22 01:16:33.985002 >   File "/home/reuben/p2pool/p2pool/main.py", line 666, in run
2015-01-22 01:16:33.985054 >     reactor.run()
2015-01-22 01:16:33.985116 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 01:16:33.985164 >     self.mainLoop()
2015-01-22 01:16:33.985208 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 01:16:33.985319 >     self.runUntilCurrent()
2015-01-22 01:16:33.985372 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 01:16:33.985417 >     call.func(*call.args, **call.kw)
2015-01-22 01:16:33.985481 > --- <exception caught here> ---
2015-01-22 01:16:33.985526 >   File "/home/reuben/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 01:16:33.985570 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 01:16:33.985617 >   File "/home/reuben/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 01:16:33.985661 >     x, handler = self._inner.get_work(*args)
2015-01-22 01:16:33.985721 >   File "/home/reuben/p2pool/p2pool/work.py", line 243, in get_work
2015-01-22 01:16:33.985767 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 01:16:33.985829 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2015-01-22 01:16:42.049091 Processing 263 shares from 24.155.164.78:3334...
2015-01-22 01:16:42.066327 ... done processing 263 shares. New: 263 Have: 3605/~17280
2015-01-22 01:16:42.066779 Requesting parent share 6722ffd2 from 1.202.128.218:9333
2015-01-22 01:16:42.068051 Peer sent entire transaction f4cd87821297c38aa5d58f997bb1d396982b75ce2161aa9e2918bc372b6db49a that was already received
2015-01-22 01:16:42.070493 P2Pool: 0 shares in chain (0 verified/3605 total) Peers: 7 (1 incoming)
2015-01-22 01:16:42.070605  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2015-01-22 01:16:42.074188 Peer sent entire transaction 4bd9cbdb1c473007ee40d0c3cb01eb25565

Is this normal?

**Comment by Rav3nPL** [comment]
Yes, it is perfectly normal on 1st run
```p2pool is downloading shares```

**Comment by bolehvpn** [comment]
Even all the unhandled errors? I don't remember seeing all those

**Comment by bolehvpn** [comment]
Tried using your version too and have the same issue. Is this something to do with twisted?

2015-01-22 02:03:11.348318 > Unhandled Error
2015-01-22 02:03:11.348700 > Traceback (most recent call last):
2015-01-22 02:03:11.348908 >   File "/home/reuben/p2pool-rav/p2pool/main.py", line 599, in run
2015-01-22 02:03:11.349092 >     reactor.run()
2015-01-22 02:03:11.349279 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 02:03:11.349453 >     self.mainLoop()
2015-01-22 02:03:11.349581 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 02:03:11.349711 >     self.runUntilCurrent()
2015-01-22 02:03:11.349833 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 02:03:11.349962 >     call.func(*call.args, **call.kw)
2015-01-22 02:03:11.350087 > --- <exception caught here> ---
2015-01-22 02:03:11.350245 >   File "/home/reuben/p2pool-rav/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 02:03:11.350412 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 02:03:11.350548 >   File "/home/reuben/p2pool-rav/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 02:03:11.350675 >     x, handler = self._inner.get_work(*args)
2015-01-22 02:03:11.350797 >   File "/home/reuben/p2pool-rav/p2pool/work.py", line 224, in get_work
2015-01-22 02:03:11.350923 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 02:03:11.351047 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2015-01-22 02:03:11.492351 > Unhandled Error
2015-01-22 02:03:11.492742 > Traceback (most recent call last):
2015-01-22 02:03:11.493083 >   File "/home/reuben/p2pool-rav/p2pool/main.py", line 599, in run
2015-01-22 02:03:11.493165 >     reactor.run()
2015-01-22 02:03:11.493209 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2015-01-22 02:03:11.493244 >     self.mainLoop()
2015-01-22 02:03:11.493434 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2015-01-22 02:03:11.493477 >     self.runUntilCurrent()
2015-01-22 02:03:11.493534 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2015-01-22 02:03:11.493584 >     call.func(*call.args, **call.kw)
2015-01-22 02:03:11.493615 > --- <exception caught here> ---
2015-01-22 02:03:11.493645 >   File "/home/reuben/p2pool-rav/p2pool/bitcoin/stratum.py", line 38, in _send_work
2015-01-22 02:03:11.493677 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2015-01-22 02:03:11.493710 >   File "/home/reuben/p2pool-rav/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2015-01-22 02:03:11.493756 >     x, handler = self._inner.get_work(*args)
2015-01-22 02:03:11.493804 >   File "/home/reuben/p2pool-rav/p2pool/work.py", line 224, in get_work
2015-01-22 02:03:11.493837 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2015-01-22 02:03:11.493866 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2015-01-22 02:03:13.294234 Peer sent entire transaction c6114c589d4fdacef544884adcc5d2cdaca5f8643ba17267d6d4f413ee5a0349 that was already received
2015-01-22 02:03:15.580630 Peer sent entire transaction 40a7062276d622c9ac1d78cc5246f70afa2cc7b87fa6cc295b396a85fe49515d that was already received
2015-01-22 02:03:15.981189 Peer sent entire transaction 40a7062276d622c9ac1d78cc5246f70afa2cc7b87fa6cc295b396a85fe49515d that was already received
2015-01-22 02:03:18.681229 Share request timed out!
2015-01-22 02:03:18.681631 Requesting parent share 7dba006d from 219.239.31.11:48042
2015-01-22 02:03:18.682778 Lost peer 78.46.88.136:9333 - Connection was aborted locally, using.
2015-01-22 02:03:20.329349 Peer sent entire transaction 2d7d9de7c97d794e2b9c3120015c3f8e2df9699d8a76fa23e7f279395c16a85b that was already received
2015-01-22 02:03:20.775311 Outgoing connection to peer 172.254.49.68:9333 established. p2pool version: 1300 '13.4-64-ga03276e-dirty'
2015-01-22 02:03:21.660734 P2Pool: 0 shares in chain (0 verified/258 total) Peers: 7 (1 incoming)
2015-01-22 02:03:21.660915  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???

**Comment by Rav3nPL** [comment]
OMG just allow it to load shares b4 you put miner on it...

**Comment by bolehvpn** [comment]
I didn't...These are from other miners trying to connect to it as they were using the p2pool before :( I can't stop them coming in anymore.

**Comment by forrestv** [comment]
It looks like you're not downloading any shares. It's possible that the
P2Pool network is partitioned due to all the bootstrap nodes being down.
Try finding an existing P2Pool node (http://p2pool-nodes.info/) and start
P2Pool with the -n option. I'll update the bootstrap nodes in P2Pool.

**Comment by bolehvpn** [comment]
Thanks so much! I went to sleep and it finally got fixed. I think you're right on the bootstrap nodes. Thanks forrestv! Also thanks Rav3nPL, you may close this issue once it's added :dancer:
