### ISSUE TITLE
p2pool is not connected to any peers (p2pool.util.jsonrpc.NarrowError: -12345)

### ISSUE THREAD

**Issue by helderdb** [p2pool/p2pool#269]
Full trace in log:

```
2015-08-31 09:11:50.285006 > Unhandled Error                                   
2015-08-31 09:11:50.285168 > Traceback (most recent call last):                
2015-08-31 09:11:50.285261 >   File "/root/p2pool/p2pool/main.py", line 666, in
 run                                                                           
2015-08-31 09:11:50.285346 >     reactor.run()                                 
2015-08-31 09:11:50.285431 >   File "/usr/lib/python2.7/dist-packages/twisted/i
nternet/base.py", line 1169, in run                                            
2015-08-31 09:11:50.285517 >     self.mainLoop()                               
2015-08-31 09:11:50.285600 >   File "/usr/lib/python2.7/dist-packages/twisted/i
nternet/base.py", line 1178, in mainLoop                                       
2015-08-31 09:11:50.285682 >     self.runUntilCurrent()                        
2015-08-31 09:11:50.285764 >   File "/usr/lib/python2.7/dist-packages/twisted/i
nternet/base.py", line 800, in runUntilCurrent                                 
2015-08-31 09:11:50.285867 >     call.func(*call.args, **call.kw)              
2015-08-31 09:11:50.285948 > --- <exception caught here> ---                   
2015-08-31 09:11:50.286056 >   File "/root/p2pool/p2pool/bitcoin/stratum.py", l
ine 38, in _send_work                                                          
2015-08-31 09:11:50.286143 >     x, got_response = self.wb.get_work(*self.wb.pr
eprocess_request('' if self.username is None else self.username))              
2015-08-31 09:11:50.286235 >   File "/root/p2pool/p2pool/work.py", line 209, in
 preprocess_request                                                            
2015-08-31 09:11:50.289506 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool 
is not connected to any peers')
2015-08-31 09:11:50.289591 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is 
not connected to any peers'
```

Running on BitcoinXT 0.11A
Have successfully run the node before but now it seems to have stopped working

**Comment by forrestv** [comment]
Try stopping P2Pool, downloading http://u.forre.st/u/itueilgg/addrs, and
replacing data/bitcoin/addrs in your p2pool directory with it. Tell me
whether that helps or not. That is a list of peers that might help if your
node can't connect to any of the bootstrap nodes.

**Comment by heldertb** [comment]
It seems to be due to a DDoS attack. Sorry for the issue

**Comment by halvors** [comment]
@heldertb Please close this issue then :)

**Comment by Xantus1** [comment]
Hey, i have an connection problem too. 

2017-04-17 09:31:25.910000 > Unhandled Error
2017-04-17 09:31:25.910000 > Traceback (most recent call last):
2017-04-17 09:31:25.910000 >   File "p2pool\main.pyc", line 669, in run
2017-04-17 09:31:25.910000 >
2017-04-17 09:31:25.910000 >   File "twisted\internet\base.pyc", line 1162, in run
2017-04-17 09:31:25.910000 >
2017-04-17 09:31:25.910000 >   File "twisted\internet\base.pyc", line 1171, in mainLoop
2017-04-17 09:31:25.926000 >
2017-04-17 09:31:25.926000 >   File "twisted\internet\base.pyc", line 793, in runUntilCurrent
2017-04-17 09:31:25.926000 >
2017-04-17 09:31:25.926000 > --- <exception caught here> ---
2017-04-17 09:31:25.926000 >   File "p2pool\bitcoin\stratum.pyc", line 38, in _send_work
2017-04-17 09:31:25.926000 >
2017-04-17 09:31:25.926000 >   File "p2pool\work.pyc", line 210, in preprocess_request
2017-04-17 09:31:25.926000 >
2017-04-17 09:31:25.926000 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers
2017-04-17 09:31:40.552000 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2017-04-17 09:31:40.552000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???

the Miner says Pool is death because no connection to the P2P network ?

i foworded port 8333, 9332 and 9333

**Comment by AndreyNag** [comment]
Hi. I have tryed many times to start p2pool classic. But always with error:
`Unhandled Error
Traceback (most recent call last):
  File "/home/root2pool/p2pool/p2pool/main.py", line 675, in run
    reactor.run()
  File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/pypy2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/root2pool/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/root2pool/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
    x, handler = self._inner.get_work(*args)
  File "/home/root2pool/p2pool/p2pool/work.py", line 247, in get_work
    raise jsonrpc.Error_for_code(-12345)(u'unknown rule activated')
p2pool.util.jsonrpc.NarrowError: -12345 unknown rule activated
2017-10-03 10:16:14.037477 P2Pool: 17370 shares in chain (17374 verified/17501 total) Peers: 8 (0 incoming)
2017-10-03 10:16:14.037608  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2017-10-03 10:16:14.037704  Shares: 0 (0 orphan, 0 dead) Stale rate: ??? Efficiency: ??? Current payout: (0.0000)=0.0000 BTC
2017-10-03 10:16:14.037788  Pool: 1536TH/s Stale rate: 17.8% Expected time to block: 36.4 days
in download_shares:
Traceback (most recent call last):
Failure: p2pool.p2p.ShareReplyError: too long

2017-10-03 10:16:14.179210 Requesting parent share 14eda5a1 from 157.25.105.194:9333
2017-10-03 10:16:14.946492 Outgoing connection to peer 178.63.18.3:9333 established. p2pool version: 1700 '17.0-4-g68f653f'
in download_shares:
Traceback (most recent call last):
Failure: p2pool.p2p.ShareReplyError: too long

2017-10-03 10:16:14.985296 Requesting parent share 14eda5a1 from 159.203.103.178:9333
in download_shares:
Traceback (most recent call last):
Failure: p2pool.p2p.ShareReplyError: too long

2017-10-03 10:16:15.431195 Requesting parent share 14eda5a1 from 157.25.105.194:9333
2017-10-03 10:16:15.451555 Peer sent entire transaction 16a941c69f2b0b061834d8bf336e101842b9f87041b59ad169710acac1366a11 that was already received
in download_shares:
Traceback (most recent call last):
Failure: p2pool.p2p.ShareReplyError: too long
`
Error is not actauly same the topic starter. My node have many peer connections and can download shares. 
Port 9332 is open and allow web connection to view statistics etc. But asic's can't connect with dead node. Startum is not working.
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)
P2pool source is dowloaded is actualy now. I have only one correction for pruned blockchain.

**Comment by fredbollinger8807** [comment]
AndreyNag 
The errors you are seeing should clear up as the node runs. They show for about the first 2 or 3 hours.
