### ISSUE TITLE
exceptions.ValueError: shares have too many txs

### ISSUE THREAD

**Issue by uujjuu** [p2pool/p2pool#274]
If I setup in bitcoin.conf

"blockmaxsize=1000000"

then it will raise this exception. Most likely because of

    max_remembered_txs_size = 2500000

in p2pool/p2p.py

I don't know enough python if it is safe or possible to double this value, but it would be nice, if you could take a look into.

The reason for blockmaxsize=1000000 is to include more transactions with more fees for everyone in the pool when solving a block.

**Comment by forrestv** [comment]
Hmm, this is worrisome. We need to be able to make 1MB blocks and the cause of that error isn't immediately apparent.

I wouldn't recommend for you to change that value. Depending on where the problem is, it could either work or split you off from the P2Pool network.

**Comment by uujjuu** [comment]
Thank you very much for your fast response! Of course I will not change anything, I just want to make sure you're aware of this problem.

Since the default of blockmaxsize is 750000 there is no surprise nobody else had this problem in the past. I tweaked the value because of a thread on bitcointalk for a little more income for miners. And of course you can only get the error if you allow lowest fee transactions so you get enough to fill the 1MB.

**Comment by jtoomim** [comment]
I'm running into this problem too.

**Comment by p3yot3** [comment]
Same here:

2016-02-19 17:55:11.831105 > Error while processing Event callbacks:
2016-02-19 17:55:11.831211 > Traceback (most recent call last):
2016-02-19 17:55:11.831237 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 74, in set
2016-02-19 17:55:11.831263 >     self.changed.happened(value)
2016-02-19 17:55:11.831287 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 42, in happened
2016-02-19 17:55:11.831311 >     func(*event)
2016-02-19 17:55:11.831335 >   File "/home/rig/p2pool/p2pool/node.py", line 243, in _
2016-02-19 17:55:11.831360 >     self.mining_txs_var.set(new_mining_txs)
2016-02-19 17:55:11.831383 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 75, in set
2016-02-19 17:55:11.831410 >     self.transitioned.happened(oldvalue, value)
2016-02-19 17:55:11.831434 > --- <exception caught here> ---
2016-02-19 17:55:11.831457 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 42, in happened
2016-02-19 17:55:11.831481 >     func(*event)
2016-02-19 17:55:11.831505 >   File "/home/rig/p2pool/p2pool/p2p.py", line 211, in update_remote_view_of_my_mining_txs
2016-02-19 17:55:11.831541 >     assert self.remote_remembered_txs_size <= self.max_remembered_txs_size
2016-02-19 17:55:11.831565 > exceptions.AssertionError: 
2016-02-19 17:55:11.833002 > Error while processing Event callbacks:
2016-02-19 17:55:11.833105 > Traceback (most recent call last):
2016-02-19 17:55:11.833132 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 74, in set
2016-02-19 17:55:11.833157 >     self.changed.happened(value)
2016-02-19 17:55:11.833182 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 42, in happened
2016-02-19 17:55:11.833206 >     func(*event)
2016-02-19 17:55:11.833230 >   File "/home/rig/p2pool/p2pool/node.py", line 243, in _
2016-02-19 17:55:11.833257 >     self.mining_txs_var.set(new_mining_txs)
2016-02-19 17:55:11.833280 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 75, in set
2016-02-19 17:55:11.833304 >     self.transitioned.happened(oldvalue, value)
2016-02-19 17:55:11.833327 > --- <exception caught here> ---
2016-02-19 17:55:11.833351 >   File "/home/rig/p2pool/p2pool/util/variable.py", line 42, in happened
2016-02-19 17:55:11.833374 >     func(*event)
2016-02-19 17:55:11.833398 >   File "/home/rig/p2pool/p2pool/p2p.py", line 211, in update_remote_view_of_my_mining_txs
2016-02-19 17:55:11.833421 >     assert self.remote_remembered_txs_size <= self.max_remembered_txs_size
2016-02-19 17:55:11.833445 > exceptions.AssertionError:

@forrestv  - any updates or news on this?

**Comment by forrestv** [comment]
Can anyone who's having a problem related to this one upload/email me their full log file? I've been looking into it for a while, and it seems that it's impossible for the failure that @p3yot3 quoted to happen in isolation. I think that there must be some other exception that gets things in a bad state first.

@p3yot3, that traceback should still be in your log file. Can you send me the whole thing?

**Comment by p3yot3** [comment]
Hi forrestv,

I just emailed the entire log file - it was too big to upload here. Hope it helps.

Regards & thanks.

**Comment by forrestv** [comment]
Thanks @p3yot3.

I'd recommend everyone test 6f114e5. It definitely fixes one part of this problem.

**Comment by luthermarcus** [comment]
Tested and agreed this did the trick.
