### ISSUE TITLE
ImportError: No module named ltc_scrypt

### ISSUE THREAD

**Issue by drazisil** [p2pool/p2pool#277]
I'm running into the following error trying to build on travis. It could be me, but looking though the codebase I can't find anything called ltc_scrypt that it would try to import. Could you shed some light on this please?

------------------------------

Error while requesting best block header:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/drazisil/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/drazisil/p2pool/p2pool/node.py", line 218, in poll_header
    handle_header((yield self.factory.conn.value.get_block_header(self.bitcoind_work.value['previous_block'])))
  File "/home/travis/build/drazisil/p2pool/p2pool/node.py", line 200, in handle_header
    if not (self.net.PARENT.POW_FUNC(bitcoin_data.block_header_type.pack(new_header)) <= self.bitcoind_work.value['bits'].target):
  File "/home/travis/build/drazisil/p2pool/p2pool/bitcoin/networks/litecoin_testnet.py", line 19, in <lambda>
    POW_FUNC = lambda data: pack.IntType(256).unpack(__import__('ltc_scrypt').getPoWHash(data))
exceptions.ImportError: No module named ltc_scrypt

**Comment by forrestv** [comment]
In the litecoin_scrypt directory, you have to run "python setup.py build",
then copy build/*/ltc_scrypt.so into the root P2Pool directory.

This is mentioned in the README.

**Comment by drazisil** [comment]
Blah. I'm sorry for wasting your timer then :-/
