### ISSUE TITLE
p2pool.util.jsonrpc.NarrowError: -10 Bitcoin is downloading blocks

### ISSUE THREAD

**Issue by dzmodest** [p2pool/p2pool#303]
```
root@security:~/p2pool# python run_p2pool.py
2016-03-22 13:27:39.377908 p2pool (version 15.0-14-g6f114e5)
2016-03-22 13:27:39.378008
2016-03-22 13:27:39.378098 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'bitcoinrpc'...
2016-03-22 13:27:39.410914 > Error getting work from bitcoind:
2016-03-22 13:27:39.410997 > Traceback (most recent call last):
2016-03-22 13:27:39.411032 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2016-03-22 13:27:39.411060 >     current.result = callback(current.result, *args, **kw)
2016-03-22 13:27:39.411088 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
2016-03-22 13:27:39.411116 >     _inlineCallbacks(r, g, deferred)
2016-03-22 13:27:39.411143 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2016-03-22 13:27:39.411176 >     result = result.throwExceptionIntoGenerator(g)
2016-03-22 13:27:39.411209 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2016-03-22 13:27:39.411238 >     return g.throw(self.type, self.value, self.tb)
2016-03-22 13:27:39.411275 > --- <exception caught here> ---
2016-03-22 13:27:39.411301 >   File "/root/p2pool/p2pool/util/deferral.py", line 41, in f
2016-03-22 13:27:39.411327 >     result = yield func(*args, **kwargs)
2016-03-22 13:27:39.411360 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2016-03-22 13:27:39.411387 >     result = result.throwExceptionIntoGenerator(g)
2016-03-22 13:27:39.411417 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2016-03-22 13:27:39.411458 >     return g.throw(self.type, self.value, self.tb)
2016-03-22 13:27:39.411495 >   File "/root/p2pool/p2pool/bitcoin/helper.py", line 48, in getwork
2016-03-22 13:27:39.411530 >     work = yield go()
2016-03-22 13:27:39.411568 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097, in _inlineCallbacks
2016-03-22 13:27:39.411595 >     result = result.throwExceptionIntoGenerator(g)
2016-03-22 13:27:39.411619 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2016-03-22 13:27:39.411644 >     return g.throw(self.type, self.value, self.tb)
2016-03-22 13:27:39.411668 >   File "/root/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2016-03-22 13:27:39.411692 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2016-03-22 13:27:39.411717 > p2pool.util.jsonrpc.NarrowError: -10 Bitcoin is downloading blocks...
^Croot@security:~/p2pool#


```

any help ?

**Comment by p3yot3** [comment]
Read the last line: "Bitcoin is downloading blocks..."

Also, please use the bitcointalk forum:

https://bitcointalk.org/index.php?topic=18313.0

**Comment by dzmodest** [comment]
@p3yot3 are you sure this is not an issue and is it normal ?
how much it would take ?

**Comment by p3yot3** [comment]
Yes - I'm sure. Please close this non-issue & use the bitcointalk thread:

https://bitcointalk.org/index.php?topic=18313.0

**Comment by dzmodest** [comment]
@p3yot3 how much it should take ?

**Comment by dzmodest** [comment]
it's done, (24H Downloading)
