### ISSUE TITLE
Errors with TRC

### ISSUE THREAD

**Issue by p3yot3** [p2pool/p2pool#304]
Using the latest repo & TRC, I'm unable to download/verify any shares, despite having connections to other peers. From what I can make out in the logs, all peers (both local & internet) seem to be getting dropped & banned immediately:

2016-04-01 12:44:05.983771 > Unhandled Error
2016-04-01 12:44:05.983924 > Traceback (most recent call last):
2016-04-01 12:44:05.983986 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:05.984044 >     reactor.run()
2016-04-01 12:44:05.984097 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:05.984153 >     self.mainLoop()
2016-04-01 12:44:05.984206 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:05.984262 >     self.runUntilCurrent()
2016-04-01 12:44:05.984315 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:05.984370 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:05.984423 > --- <exception caught here> ---
2016-04-01 12:44:05.984476 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:05.984531 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:05.984588 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:05.984643 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:05.984696 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:05.984750 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:05.984804 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:08.781101 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 1 (0 incoming)
2016-04-01 12:44:08.781262  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:44:10.988951 > Unhandled Error
2016-04-01 12:44:10.989157 > Traceback (most recent call last):
2016-04-01 12:44:10.991404 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:10.991611 >     reactor.run()
2016-04-01 12:44:10.991690 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:10.991787 >     self.mainLoop()
2016-04-01 12:44:10.991859 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:10.992017 >     self.runUntilCurrent()
2016-04-01 12:44:10.992094 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:10.992168 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:10.992238 > --- <exception caught here> ---
2016-04-01 12:44:10.992320 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:10.992394 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:10.992477 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:10.992551 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:10.992629 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:10.992701 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:10.992775 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:13.451577 Outgoing connection to peer 195.208.39.210:9323 established. p2pool version: 1500 '15.0'
2016-04-01 12:44:13.610809 Peer sent entire transaction e5071caac7dd9e8fe093607a179b758ac0e22b37407461ba9566c9e853b19fc0 that was already received
2016-04-01 12:44:14.781952 P2Pool: 0 shares in chain (0 verified/1 total) Peers: 2 (0 incoming)
2016-04-01 12:44:14.782104  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:44:15.995824 > Unhandled Error
2016-04-01 12:44:15.995927 > Traceback (most recent call last):
2016-04-01 12:44:15.995963 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:15.995989 >     reactor.run()
2016-04-01 12:44:15.996012 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:15.996036 >     self.mainLoop()
2016-04-01 12:44:15.996060 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:15.996084 >     self.runUntilCurrent()
2016-04-01 12:44:15.996106 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:15.996130 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:15.996153 > --- <exception caught here> ---
2016-04-01 12:44:15.996176 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:15.996199 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:15.996224 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:15.996248 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:15.996271 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:15.996294 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:15.996316 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:17.782442 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:44:17.782601  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:44:21.000070 > Unhandled Error
2016-04-01 12:44:21.000237 > Traceback (most recent call last):
2016-04-01 12:44:21.002485 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:21.002631 >     reactor.run()
2016-04-01 12:44:21.002690 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:21.002750 >     self.mainLoop()
2016-04-01 12:44:21.002877 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:21.002955 >     self.runUntilCurrent()
2016-04-01 12:44:21.003025 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:21.003095 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:21.003165 > --- <exception caught here> ---
2016-04-01 12:44:21.003234 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:21.003321 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:21.003399 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:21.003473 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:21.003543 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:21.003614 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:21.003682 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:26.007912 > Unhandled Error
2016-04-01 12:44:26.008087 > Traceback (most recent call last):
2016-04-01 12:44:26.010230 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:26.010366 >     reactor.run()
2016-04-01 12:44:26.010425 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:26.010508 >     self.mainLoop()
2016-04-01 12:44:26.010563 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:26.010618 >     self.runUntilCurrent()
2016-04-01 12:44:26.010672 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:26.010728 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:26.010785 > --- <exception caught here> ---
2016-04-01 12:44:26.010840 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:26.010893 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:26.010950 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:26.011005 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:26.011056 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:26.011109 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:26.011161 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:31.015313 > Unhandled Error
2016-04-01 12:44:31.015535 > Traceback (most recent call last):
2016-04-01 12:44:31.017794 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:31.017951 >     reactor.run()
2016-04-01 12:44:31.018029 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:31.018181 >     self.mainLoop()
2016-04-01 12:44:31.018260 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:31.018349 >     self.runUntilCurrent()
2016-04-01 12:44:31.018422 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:31.018503 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:31.018584 > --- <exception caught here> ---
2016-04-01 12:44:31.018655 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:31.018728 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:31.018803 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:31.018875 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:31.018964 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:31.019039 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:31.019112 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:32.784021 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:44:32.784180  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:44:36.023378 > Unhandled Error
2016-04-01 12:44:36.023542 > Traceback (most recent call last):
2016-04-01 12:44:36.025666 >   File "/home/rig/p2pool/p2pool/main.py", line 669, in run
2016-04-01 12:44:36.025839 >     reactor.run()
2016-04-01 12:44:36.025920 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
2016-04-01 12:44:36.026011 >     self.mainLoop()
2016-04-01 12:44:36.026088 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1201, in mainLoop
2016-04-01 12:44:36.026168 >     self.runUntilCurrent()
2016-04-01 12:44:36.026241 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
2016-04-01 12:44:36.026317 >     call.func(*call.args, **call.kw)
2016-04-01 12:44:36.026388 > --- <exception caught here> ---
2016-04-01 12:44:36.026459 >   File "/home/rig/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
2016-04-01 12:44:36.026541 >     x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
2016-04-01 12:44:36.026655 >   File "/home/rig/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
2016-04-01 12:44:36.026734 >     x, handler = self._inner.get_work(*args)
2016-04-01 12:44:36.026812 >   File "/home/rig/p2pool/p2pool/work.py", line 245, in get_work
2016-04-01 12:44:36.026888 >     raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
2016-04-01 12:44:36.026963 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
2016-04-01 12:44:47.785680 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:44:47.785851  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:45:02.788004 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:45:02.788184  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:45:17.790098 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:45:17.790267  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:45:27.234247 Peer 192.168.1.5:37371 misbehaving, will drop and ban. Reason: was connected to self
2016-04-01 12:45:27.234446 Bad peer banned: ('192.168.1.5', 37371)
2016-04-01 12:45:27.235737 Peer 192.168.1.5:9323 misbehaving, will drop and ban. Reason: was connected to self
2016-04-01 12:45:27.235894 Bad peer banned: ('192.168.1.5', 9323)
2016-04-01 12:45:32.792372 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:45:32.792533  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:45:47.794699 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:45:47.794873  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:46:02.796428 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:46:02.796599  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:46:17.798264 P2Pool: 0 shares in chain (0 verified/2 total) Peers: 2 (0 incoming)
2016-04-01 12:46:17.798433  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:46:32.800037 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:46:32.800227  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:46:47.801375 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:46:47.801474  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:47:02.803019 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:47:02.803188  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:47:17.804493 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:47:17.804594  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:47:32.806488 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:47:32.806669  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:47:34.519405 Skipping from block 464a35610998dd2bf14c7b28fd9be6f5177e03a31dbfa6b8a0e to block d692ff6ed55a3a8a194ec0a205fc7a769189c63112e939b55e6!
2016-04-01 12:47:47.808673 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:47:47.808854  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:48:02.810203 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:48:02.810384  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:48:17.811972 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:48:17.812181  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:48:32.813708 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:48:32.813890  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:48:47.815384 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:48:47.815576  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:49:02.817781 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:49:02.817961  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:49:17.820677 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:49:17.820863  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:49:32.823069 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:49:32.823255  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:49:43.593010 Handshake timed out, disconnecting from 77.249.199.235:29932
2016-04-01 12:49:47.825058 P2Pool: 0 shares in chain (0 verified/3 total) Peers: 2 (0 incoming)
2016-04-01 12:49:47.825238  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:49:53.826682 P2Pool: 0 shares in chain (0 verified/4 total) Peers: 2 (0 incoming)
2016-04-01 12:49:53.826871  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:50:08.829469 P2Pool: 0 shares in chain (0 verified/4 total) Peers: 2 (0 incoming)
2016-04-01 12:50:08.829725  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:50:23.831818 P2Pool: 0 shares in chain (0 verified/4 total) Peers: 2 (0 incoming)
2016-04-01 12:50:23.832003  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:50:38.834570 P2Pool: 0 shares in chain (0 verified/4 total) Peers: 2 (0 incoming)
2016-04-01 12:50:38.834757  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2016-04-01 12:50:53.837626 P2Pool: 0 shares in chain (0 verified/5 total) Peers: 2 (0 incoming)
2016-04-01 12:50:53.837850  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???

Any ideas?

Thanks.

**Comment by forrestv** [comment]
The only peers that were banned were connections to yourself.

You're unable to download the sharechain, either because you're not
connected to the main network due to a lack of hardcoded seed nodes being
up, in which case you should find a peer's IP address and use the -n option
to specify it, or perhaps because nobody is using the TRC sharechain and it
was lost. If the latter's the case, it's possible to restart it, though you
probably wouldn't want to being that nobody else is using it.

**Comment by p3yot3** [comment]
Hi forrest,

Thanks for the quick reply. OK, 2 questions if you don't mind - how can I stop p2pool connecting to itself & how can I restart the TRC sharechain?

TRC has been taken over recently & is currently undergoing a code revamp, so I'd like to get TRC up & running with p2pool again in the hope of encouraging new miners.

Thanks again.

**Comment by forrestv** [comment]
1. P2Pool bans itself from connecting to itself and it ends there.

2. You have to set PERSIST = False for TRC and then mine. P2Pool will start
a new sharechain instead of insisting of joining an existing one. Also,
make sure that there are a few working seed nodes listing in the TRC
configuration.

**Comment by p3yot3** [comment]
So, I add:

` --PERSIST = False`

 to the TRC p2pool startup command?

**Comment by forrestv** [comment]
Sorry, no, you have to modify terracoin.py in p2pool/networks.

**Comment by p3yot3** [comment]
Ah - got it. If I manage to create a new TRC sharechain. I presume this should be removed before a restart or when a few nodes pick it up?

Sorry for the questions - I really appreciate your input.

**Comment by forrestv** [comment]
It doesn't really matter, but yes, remove it once you've mined a few shares
and waited an hour or so to ensure it's saved to disk. It just shouldn't be
present in public versions to prevent users from mining alone when they're
having connection problems.

**Comment by p3yot3** [comment]
Understood.

And TRCp2pool versions <v15 - can they connect? I'm thinking specifically of Rav3n_pl's fork which is used quite widely.

Thanks.

**Comment by forrestv** [comment]
Everyone has to be on the same major version. Major versions designate
hardforks. So, no.

**Comment by p3yot3** [comment]
Struggling.......
