### ISSUE TITLE
Error on make: setuptools failed

### ISSUE THREAD

**Issue by myin142** [p2pool/p2pool#335]
```
rm -rf "/home/sakkaku/Downloads/p2pool/.pyenv"
mkdir -p "/home/sakkaku/Downloads/p2pool/.pyenv"
tar \
    -C "/home/sakkaku/Downloads/p2pool/.cache"/pyenv --gzip \
    -xf "/home/sakkaku/Downloads/p2pool/.cache"/pyenv/virtualenv-1.11.6.tar.gz
python "/home/sakkaku/Downloads/p2pool/.cache"/pyenv/virtualenv-1.11.6/virtualenv.py \
    --clear \
    --distribute \
    --never-download \
    --prompt="(p2pool) " \
    "/home/sakkaku/Downloads/p2pool/.pyenv"
Not deleting /home/sakkaku/Downloads/p2pool/.pyenv/bin
Using base prefix '/usr'
New python executable in /home/sakkaku/Downloads/p2pool/.pyenv/bin/python
Installing setuptools, pip...
  Complete output from command /home/sakkaku/Downlo...ol/.pyenv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv_support/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/pkg_resources.py", line 1479, in <module>
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv.py", line 2338, in <module>
    main()
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/sakkaku/Downloads/p2pool/.cache/pyenv/virtualenv-1.11.6/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/sakkaku/Downlo...ol/.pyenv/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make: *** [Makefile:61: /home/sakkaku/Downloads/p2pool/.cache/pyenv/pyenv-1.11.6-base.tar.gz] Error 1
```

**Comment by samsaga2** [comment]
Make sure you are using python2.6 or python2.7

**Comment by farsider350** [comment]
No need to make, just run.

 #411
