### ISSUE TITLE
Using pruned blockchain on p2pool nodes.

### ISSUE THREAD

**Issue by ilsawa** [p2pool/p2pool#339]
If on the node of the p2pool use pruned blockchain, you will see an error message:

```
File "/opt/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -32603 Block not available (pruned data)
```

This is easy to fix, in fact, it does not need blockchain for anything, except for checking that the start is actually done with bitcoind. In the p2pool/p2pool/bitcoin/networks/bitcoin.py file, you can replace this:

```
RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
            (yield helper.check_genesis_block(bitcoind, '000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f')) and
            not (yield bitcoind.rpc_getinfo())['testnet']
        ))
```

On this:

```
RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
            'bitcoin' in (yield bitcoind.rpc_help()) and
            not (yield bitcoind.rpc_getinfo())['testnet']
        ))
```

After that, it will start with a pruned client and will work normally.

This is relevant for Bitcoin CORE: v.0.14.x

**Comment by ChainQuery** [comment]
I believe when P2Pool has an orphan block (has no happened in a long time, but has a non-negligible probability) the node would have to redownload and reindex the whole blockchain?

**Comment by CryptoManiac** [comment]
@ChainQuery you would need a chain of few thousand orphaned blocks to have any issues with pruned client.

**Comment by p3yot3** [comment]
Can this patch be applied to the latest v17.0 of p2pool also?

**Comment by ilsawa** [comment]
Yes, of course.
Just make a blockchain least 2 Gigabit

**Comment by adelorenzo** [comment]
Anyone managed to get p2pool to work with a pruned bitcoind? I patched the bitcoin.py as suggested and now the problem is the following output when I start run_p2pool.py:

Error getting work from bitcoind:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/opt/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/p2pool/p2pool/bitcoin/helper.py", line 53, in getwork
    work = yield go()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/opt/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -10 Bitcoin is downloading `blocks...

- VPS Ubuntu 16.04.3 server
- Bitcoin Core Daemon version v0.14.2.0-gfc61c83
- 30GB of RAM
- 2TB HD
- 6 core CPU

Thanks!

**Comment by BaalMcKloud** [comment]
p2pool.util.jsonrpc.NarrowError: -10 Bitcoin is downloading `blocks...

Bitcoin is downloading Blocks.

**Comment by gregturn** [comment]
I applied the patch and all I get is this:

```
2018-01-14 09:39:03.124106 p2pool (version 17.0-9-g27255ec-dirty)
2018-01-14 09:39:03.124213 
2018-01-14 09:39:03.124318 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'bbitcboinrpct'...
2018-01-14 09:39:03.127580 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:04.131593 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:05.134164 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:06.136897 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:07.139602 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:08.142829 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:09.145298 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:10.148096 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:11.150733 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-01-14 09:39:12.153131 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
```

**Comment by ilsawa** [comment]
This is relevant for Bitcoin CORE: v.0.14.x

**Comment by Alan911Black** [comment]
@ilsawa
Hi Guys, 
@gregturn did you able to solve that issue? i got this error also:

2018-01-29 18:27:24.376732 p2pool (version 17.0-9-g27255ec)
2018-01-29 18:27:24.376830 
2018-01-29 18:27:24.376920 Testing bitcoind RPC connection to 'http://127.0.0.1:10332/' with username 'xxxxxxx'...
2018-01-29 18:27:24.381516 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!

PLEASE, any help...thanks!

**Comment by gregturn** [comment]
Nope @alan911black.

**Comment by ilsawa** [comment]
For Bitcoin CORE: v.0.15.x

> RPC_CHECK = defer.inlineCallbacks(lambda bitcoind: defer.returnValue(
>             (yield bitcoind.rpc_getblockchaininfo())['chain'] != 'test'
>         ))

**Comment by Alan911Black** [comment]
@ilsawa Thanks!
but it didnt work, i download my pool from p2pool git, i changed the file p2pool/p2pool/bitcoin/networks/bitcoin.py

i still got the same error
2018-01-30 18:09:43.110091 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
do i need to do anything else? do i need to download the bitcoin blockchain

**Comment by farsider350** [comment]
#411

**Comment by says112** [comment]
Hello! I started dgb on f2pool but I have this error.How can it be fixed? Sincerely, Alexander!
![Снимок экрана (271)](https://user-images.githubusercontent.com/22127398/198139791-3daec87c-f86f-4a73-ae7b-90f06f7d739a.png)
