### ISSUE TITLE
p2pool dont connect

### ISSUE THREAD

**Issue by Xantus1** [p2pool/p2pool#342]
Hi people,

i using an oparation system from microsot windows 10Home.

after reading the Readme file i do this sucessful :
> Windows:
> * Install Python 2.7: http://www.python.org/getit/
- done 👍 
> * Install Twisted: http://twistedmatrix.com/trac/wiki/Downloads
- done  👍 
> * Install Zope.Interface: http://pypi.python.org/pypi/zope.interface/3.8.0
- done 👍 
> * Install python win32 api: http://sourceforge.net/projects/pywin32/files/pywin32/Build%20218/
- well, hopfully done , with following error message i do not understand : 
   "close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr"
> * Install python win32 api wmi wrapper: https://pypi.python.org/pypi/WMI/#downloads
- done 👍 
> * Unzip the files into C:\Python27\Lib\site-packages
- done , extracted complete folder located in zip to "C:\Python27\Lib\site-packages"

after starting p2Pool i see following lines : 
 
Twisted doesn't have abortConnection! Upgrade to a newer version of Twisted to avoid memory leaks!
Pausing for 3 seconds...
2017-04-17 12:10:57.079000 p2pool (version 16.0)
2017-04-17 12:10:57.079000
2017-04-17 12:10:57.079000 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'Xantus'...
2017-04-17 12:10:58.344000     ...success!
2017-04-17 12:10:58.344000     Current block hash: 19305011856da611c0390ddfd87430fb639f0347344f348
2017-04-17 12:10:58.344000     Current block height: 462273
2017-04-17 12:10:58.344000
2017-04-17 12:10:58.344000 Testing bitcoind P2P connection to '127.0.0.1:8333'...
2017-04-17 12:10:58.344000     ...success!
2017-04-17 12:10:58.344000
2017-04-17 12:10:58.344000 Determining payout address...
2017-04-17 12:10:58.344000     Loaded cached address: 1KRLVcE3yNHPWZMXeGG5rwtuPdrretaQfp...
2017-04-17 12:10:58.360000     ...success! Payout address: 1KRLVcE3yNHPWZMXeGG5rwtuPdrretaQfp
2017-04-17 12:10:58.360000
2017-04-17 12:10:58.360000 Loading shares...
2017-04-17 12:10:58.360000     ...done loading 0 shares (0 verified)!
2017-04-17 12:10:58.360000
2017-04-17 12:10:58.360000 Initializing work...
2017-04-17 12:11:00.095000     ...success!
2017-04-17 12:11:00.095000
2017-04-17 12:11:00.095000 Joining p2pool network using port 9333...
2017-04-17 12:11:00.095000 > Unhandled Error
2017-04-17 12:11:00.110000 > Traceback (most recent call last):
2017-04-17 12:11:00.110000 > Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'vps.forre.st' not found: [Errno 11001] getaddrinfo failed.
2017-04-17 12:11:00.595000     ...success!
2017-04-17 12:11:00.595000
2017-04-17 12:11:00.595000 Listening for workers on '' port 9332...
2017-04-17 12:11:00.642000     ...success!
2017-04-17 12:11:00.642000
2017-04-17 12:11:00.642000 Started successfully!
2017-04-17 12:11:00.642000 Go to http://127.0.0.1:9332/ to view graphs and statistics!
2017-04-17 12:11:00.642000 Donating 1.0% of work towards P2Pool's development. Thank you!
2017-04-17 12:11:00.657000 You can increase this amount with --give-author argument! (or decrease it, if you must)
2017-04-17 12:11:00.657000
2017-04-17 12:11:03.657000 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2017-04-17 12:11:03.657000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???
2017-04-17 12:11:04.532000 > Unhandled Error
2017-04-17 12:11:04.532000 > Traceback (most recent call last):
2017-04-17 12:11:04.548000 >   File "p2pool\main.pyc", line 669, in run
2017-04-17 12:11:04.548000 >
2017-04-17 12:11:04.548000 >   File "twisted\internet\base.pyc", line 1162, in run
2017-04-17 12:11:04.548000 >
2017-04-17 12:11:04.548000 >   File "twisted\internet\base.pyc", line 1171, in mainLoop
2017-04-17 12:11:04.548000 >
2017-04-17 12:11:04.548000 >   File "twisted\internet\base.pyc", line 793, in runUntilCurrent
2017-04-17 12:11:04.548000 >
2017-04-17 12:11:04.548000 > --- <exception caught here> ---
2017-04-17 12:11:04.548000 >   File "p2pool\bitcoin\stratum.pyc", line 38, in _send_work
2017-04-17 12:11:04.564000 >
2017-04-17 12:11:04.564000 >   File "p2pool\work.pyc", line 210, in preprocess_request
2017-04-17 12:11:04.564000 >
2017-04-17 12:11:04.564000 > p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers
2017-04-17 12:11:18.706000 P2Pool: 0 shares in chain (0 verified/0 total) Peers: 0 (0 incoming)
2017-04-17 12:11:18.706000  Local: 0H/s in last 0.0 seconds Local dead on arrival: ??? Expected time to share: ???

Error an Status messages repeads an my miner sys Pool is death.

Does someone see my misstake? wath could be my trouble ?

**Comment by BaalMcKloud** [comment]
`2017-04-17 12:11:00.110000 > Failure: twisted.internet.error.DNSLookupError: DNS lookup failed: address 'vps.forre.st' not found: [Errno 11001] getaddrinfo failed.`

the seednode ist down. you have to use a other seednode.

**Comment by Xantus1** [comment]
Thanks much BaalMcKloud.

i started witch -n p2pool.org
now it seams to run ... 

up to now i do my test with an old small raspery Pi miner (only 5Gh/s)
it seams to work. ^^ sweet

**Comment by Dasky26** [comment]
@Xantus1  tell me pls how to do ??

**Comment by farsider350** [comment]
python run_p2pool.py -n p2pool.org @Dasky26
