### ISSUE TITLE
p2pool.util.jsonrpc.narrowerror: -8 support for 'segwit' rule requires explicit client support.

### ISSUE THREAD

**Issue by hgslyh** [p2pool/p2pool#343]
2017-05-21 20:59:41.313000 p2pool (version 11.2)
2017-05-21 20:59:41.313000
2017-05-21 20:59:41.313000 Testing bitcoind RPC connection to 'http://127.0.0.1:
10332/' with username 'hgslyh'...
2017-05-21 20:59:41.406000 > Error getting work from bitcoind:
2017-05-21 20:59:41.406000 > Traceback (most recent call last):
2017-05-21 20:59:41.422000 >   File "twisted\internet\defer.pyc", line 551, in _
runCallbacks
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "twisted\internet\defer.pyc", line 1101, in
gotResult
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "twisted\internet\defer.pyc", line 1043, in
_inlineCallbacks
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "twisted\python\failure.pyc", line 382, in t
hrowExceptionIntoGenerator
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 > --- <exception caught here> ---
2017-05-21 20:59:41.422000 >   File "p2pool\util\deferral.pyc", line 41, in f
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "twisted\internet\defer.pyc", line 1043, in
_inlineCallbacks
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "twisted\python\failure.pyc", line 382, in t
hrowExceptionIntoGenerator
2017-05-21 20:59:41.422000 >
2017-05-21 20:59:41.422000 >   File "p2pool\bitcoin\helper.pyc", line 36, in get
work
2017-05-21 20:59:41.438000 >
2017-05-21 20:59:41.438000 >   File "twisted\internet\defer.pyc", line 1043, in
_inlineCallbacks
2017-05-21 20:59:41.438000 >
2017-05-21 20:59:41.438000 >   File "twisted\python\failure.pyc", line 382, in t
hrowExceptionIntoGenerator
2017-05-21 20:59:41.453000 >
2017-05-21 20:59:41.453000 >   File "p2pool\util\jsonrpc.pyc", line 133, in _htt
p_do
2017-05-21 20:59:41.453000 >
2017-05-21 20:59:41.453000 > p2pool.util.jsonrpc.NarrowError: -8 Support for 'se
gwit' rule requires explicit client support

**Comment by GatekeeperZA** [comment]
having same issue as above does anyone please have a fix for this .. ?

**Comment by takenek** [comment]
Same issue here.

**Comment by GatekeeperZA** [comment]
any fixes again.. ?

**Comment by ZorakIT** [comment]
-8 Support for 'segwit' rule requires explicit client support

same error here, any suggestions?

**Comment by veqtrus** [comment]
What altcoin are you mining?

**Comment by dbeckwith** [comment]
same error mining litecoin

**Comment by veqtrus** [comment]
Segwit is activated on litecoin but p2pool doesn't support it yet. You will have to run #327 until it is merged.

**Comment by p3yot3** [comment]
When/if dev bothers merging - will p2pool still be able to be used with non-segwit altcoins?

**Comment by veqtrus** [comment]
@p3yot3 yes; segwit supports needs to be explicitly indicated in the coin's parameters.

**Comment by farsider350** [comment]
Segwit Activated P2pool Install Guide #411
