### ISSUE TITLE
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 3: unexpected end of data.

### ISSUE THREAD

**Issue by hgslyh** [p2pool/p2pool#344]
Twisted doesn't have abortConnection! Upgrade to a newer version of Twisted to avoid memory leaks!
Pausing for 3 seconds...
2017-05-21 21:39:12.687000 p2pool (version 16.0)
2017-05-21 21:39:12.703000
2017-05-21 21:39:12.703000 Testing bitcoind RPC connection to 'http://127.0.0.1:10332/' with username 'hgslyh'...
2017-05-21 21:39:12.875000 > Error while checking Bitcoin connection:
2017-05-21 21:39:12.875000 > Traceback (most recent call last):
2017-05-21 21:39:12.875000 >   File "twisted\internet\defer.pyc", line 542, in _runCallbacks
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 >   File "twisted\internet\defer.pyc", line 1076, in gotResult
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 >   File "twisted\internet\defer.pyc", line 1018, in _inlineCallbacks
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 >   File "twisted\python\failure.pyc", line 350, in throwExceptionIntoGenerator
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 > --- <exception caught here> ---
2017-05-21 21:39:12.875000 >   File "p2pool\util\deferral.pyc", line 41, in f
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 >   File "twisted\internet\defer.pyc", line 1018, in _inlineCallbacks
2017-05-21 21:39:12.875000 >
2017-05-21 21:39:12.875000 >   File "twisted\python\failure.pyc", line 350, in throwExceptionIntoGenerator
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "p2pool\bitcoin\helper.pyc", line 13, in check
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "twisted\internet\defer.pyc", line 1018, in _inlineCallbacks
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "twisted\python\failure.pyc", line 350, in throwExceptionIntoGenerator
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "p2pool\bitcoin\networks\litecoin.pyc", line 16, in <lambda>
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "twisted\internet\defer.pyc", line 1020, in _inlineCallbacks
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.890000 >   File "p2pool\util\jsonrpc.pyc", line 128, in _http_do
2017-05-21 21:39:12.890000 >
2017-05-21 21:39:12.906000 >   File "json\__init__.pyc", line 326, in loads
2017-05-21 21:39:12.906000 >
2017-05-21 21:39:12.906000 >   File "json\decoder.pyc", line 366, in decode
2017-05-21 21:39:12.906000 >
2017-05-21 21:39:12.906000 >   File "json\decoder.pyc", line 382, in raw_decode
2017-05-21 21:39:12.906000 >
2017-05-21 21:39:12.906000 > exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 3: unexpected end of data.

**Comment by farsider350** [comment]
#411
