### ISSUE TITLE
run litecoin error

### ISSUE THREAD

**Issue by cxinny** [p2pool/p2pool#350]
python run_p2pool.py --net litecoin
2017-08-23 10:19:23.721635 p2pool (version 16.0-4-gde1be30)
2017-08-23 10:19:23.721704 
2017-08-23 10:19:23.721757 Testing bitcoind RPC connection to 'http://127.0.0.1:9332/' with username 'test'...
2017-08-23 10:19:23.757147 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2017-08-23 10:19:24.762491 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!

**Comment by rldleblanc** [comment]
I'm getting the same thing. It is picking up the correct information form litecoin.conf. I'v tried 0.14.2 and master of litecoind. I've tried 15.0, 16.0 and master of p2pool. Any help would be appreciated.

**Comment by rldleblanc** [comment]
It looks like it can connect. If I start up p2pool before litecoin is completely started up, it is able to get the status.
```
2017-08-23 21:25:00.131004 > Error while checking Bitcoin connection:
2017-08-23 21:25:00.131095 > Traceback (most recent call last):
2017-08-23 21:25:00.131128 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
2017-08-23 21:25:00.131158 >     current.result = callback(current.result, *args, **kw)
2017-08-23 21:25:00.131186 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155,in gotResult
2017-08-23 21:25:00.131215 >     _inlineCallbacks(r, g, deferred)
2017-08-23 21:25:00.131239 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097,in _inlineCallbacks
2017-08-23 21:25:00.131265 >     result = result.throwExceptionIntoGenerator(g)
2017-08-23 21:25:00.131289 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2017-08-23 21:25:00.131353 >     return g.throw(self.type, self.value, self.tb)
2017-08-23 21:25:00.131398 > --- <exception caught here> ---
2017-08-23 21:25:00.131426 >   File "/home/rleblanc/p2pool/p2pool/util/deferral.py", line 41, in f
2017-08-23 21:25:00.131454 >     result = yield func(*args, **kwargs)
2017-08-23 21:25:00.131481 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097,in _inlineCallbacks
2017-08-23 21:25:00.131514 >     result = result.throwExceptionIntoGenerator(g)
2017-08-23 21:25:00.131549 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2017-08-23 21:25:00.131582 >     return g.throw(self.type, self.value, self.tb)
2017-08-23 21:25:00.131619 >   File "/home/rleblanc/p2pool/p2pool/bitcoin/helper.py", line 13, in check
2017-08-23 21:25:00.131653 >     if not (yield net.PARENT.RPC_CHECK(bitcoind)):
2017-08-23 21:25:00.131681 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097,in _inlineCallbacks
2017-08-23 21:25:00.131709 >     result = result.throwExceptionIntoGenerator(g)
2017-08-23 21:25:00.131735 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2017-08-23 21:25:00.131762 >     return g.throw(self.type, self.value, self.tb)
2017-08-23 21:25:00.131785 >   File "/home/rleblanc/p2pool/p2pool/bitcoin/networks/litecoin.py", line 15, in<lambda>
2017-08-23 21:25:00.131825 >
2017-08-23 21:25:00.131857 >   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1097,in _inlineCallbacks
2017-08-23 21:25:00.131895 >     result = result.throwExceptionIntoGenerator(g)
2017-08-23 21:25:00.131928 >   File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
2017-08-23 21:25:00.131955 >     return g.throw(self.type, self.value, self.tb)
2017-08-23 21:25:00.131994 >   File "/home/rleblanc/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
2017-08-23 21:25:00.132026 >     raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
2017-08-23 21:25:00.132071 > p2pool.util.jsonrpc.NarrowError: -28 Rewinding blocks...
2017-08-23 21:25:01.135992 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2017-08-23 21:25:02.139784 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2017-08-23 21:25:03.143815 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
```

**Comment by silonc** [comment]
It would appear to be [this line](https://github.com/p2pool/p2pool/blob/de1be30c638173292b6626fe90f154b9cba6e4ad/p2pool/bitcoin/networks/litecoin.py#L15) that is not returning correctly anymore. 

I would need to take the time to dig deeper on what operation is performed there and see what changed that caused this to break. I'm just now taking the time to dig through the source code in the crypto world so I don't know off hand why exactly it's broken.

Removing that line from the code, while probably not a good idea, resolved the issue for me.

**Comment by cxinny** [comment]
Can not work properly @silonc

**Comment by ApatheticCosmos** [comment]
I'm having this issue as well. @silonc can you share the code change you got it to work? That variable seems needed, and deleting it breaks the program.

**Comment by rldleblanc** [comment]
https://github.com/p2pool/p2pool/pull/356 seems to fix it. Shamelessly pulled from https://github.com/ilsawa/p2pool-ltc.

**Comment by silonc** [comment]
@cxinny @ApatheticCosmos I was at least able to gain a connection to the litecoin client, but spent a fair amount of time trying to figure out the error following. Sorry for not following up on that here. I will try the fix posted by @rldleblanc later this evening for a fully functioning fix.

**Comment by rldleblanc** [comment]
If it works for you, let me know. I don't have enough hash to test.

LfSpWMybzvoWgzhUV1uBUhbczr1LZXeQK5

**Comment by cxinny** [comment]
@silonc yes,it connect to the litecoin client, but the work isn't working properly

**Comment by cxinny** [comment]
@rldleblanc it's ok,run ok

**Comment by rldleblanc** [comment]
I'm getting almost 100% dead shares with 17.0 and I have messages like this.
 Worker <worker ID> submitted share with hash > target:

The other p2pool I referenced has almost no dead shares...

**Comment by dtlgc** [comment]
rldleblanc 
Did you find a solution to

**Comment by rldleblanc** [comment]
@dtlgc No, I haven't looked into it any more, I've just been using p2pool-ltc for the time being. I've been wanting to merge all the alts that I'm using into the p2pool base and get them all up to date instead of having so many outdated forks of p2pool. But real life and other more pressing projects have been consuming my time.

**Comment by farsider350** [comment]
#356 If we can get this pushed to master it will fix the issue.
