### ISSUE TITLE
p2pool - not support litecoin daemon v 0.15.1

### ISSUE THREAD

**Issue by DJMorgan** [p2pool/p2pool#379]
p2pool - litecoin- is the build not relevant? V0.15.1
with the latest litecoind daemon failed to start no connection with the demon.
` >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!`
There will be a version compatible with p2pool Litecoin daemon v 0.15.1 ?

**Comment by DJMorgan** [comment]
```
2018-03-04 16:17:27.389882 Testing bitcoind RPC connection to 'http://127.0.0.1:9332/' with username 'xxxxxx'...
2018-03-04 16:17:27.392521 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
2018-03-04 16:17:28.395309 >     Check failed! Make sure that you're connected to the right bitcoind with --bitcoind-rpc-port!
```

**Comment by cybernoc** [comment]
it works....

but give me errors like 

Unhandled Error
Traceback (most recent call last):
  File "/p2pool/p2pool.old/p2pool/main.py", line 675, in run
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/p2pool/p2pool.old/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/p2pool/p2pool.old/p2pool/work.py", line 210, in preprocess_request
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is not connected to any peers')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is not connected to any peers

**Comment by farsider350** [comment]
most people have moved onto the Jtoomim chain I'm sure github.com/jtoomim/p2pool

**Comment by farsider350** [comment]
@DJMorgan You need "--net litecoin" in the command line when you run it. Hope you got it sorted.
@cybernoc Bootstraps need updating. If let run long enough you should find peers.
