### ISSUE TITLE
p2pool solo mining issues

### ISSUE THREAD

**Issue by ikolubr** [p2pool/p2pool#389]
Hi @forrestv,
I'm doing some tests on p2pool "solo" mining so I can make it work for other altcoins... to start a new sharechain...

I'm testing it with litecoin for now and I get this error everytime I want to start a new sharechain:

```python
2018-03-27 09:47:00.566383 Total block stripped size=112635 B, full size=143075 B,  weight: 480900 WU
Unhandled Error
Traceback (most recent call last):
  File "/home/user/p2pooljtoomim/p2pool/main.py", line 692, in run
    reactor.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/home/user/p2pooljtoomim/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/home/user/p2pooljtoomim/p2pool/bitcoin/worker_interface.py", line 129, in get_work
    x, handler = self._inner.get_work(*args)
  File "/home/user/p2pooljtoomim/p2pool/work.py", line 337, in get_work
    base_subsidy=self.node.net.PARENT.SUBSIDY_FUNC(self.current_work.value['height']),
  File "/home/user/p2pooljtoomim/p2pool/data.py", line 259, in generate_transaction
    raise ValueError('segwit transaction included before activation')
exceptions.ValueError: segwit transaction included before activation
```

The only file I changes was the p2pool/networks/litecoin.py to:

```python
from p2pool.bitcoin import networks

PARENT = networks.nets['litecoin']
SHARE_PERIOD = 30 # seconds
CHAIN_LENGTH = 24*60*60//10 # shares
REAL_CHAIN_LENGTH = 24*60*60//10 # shares
TARGET_LOOKBEHIND = 20 # shares
SPREAD = 12 # blocks
IDENTIFIER = 'a777d5b8c6923410'.decode('hex')
PREFIX = '7778c1a53ef629b0'.decode('hex')
P2P_PORT = 9329
MIN_TARGET = 0
MAX_TARGET = 2**256//2**20 - 1
PERSIST = False
WORKER_PORT = 9320
BOOTSTRAP_ADDRS = ''.split(' ')
ANNOUNCE_CHANNEL = '#p2pool-ltc'
VERSION_CHECK = lambda v: None if 100400 <= v else 'Litecoin version too old. Upgrade to 0.10.4 or newer!'
VERSION_WARNING = lambda v: None
SOFTFORKS_REQUIRED = set(['bip65', 'csv', 'segwit'])
MINIMUM_PROTOCOL_VERSION = 1600
NEW_MINIMUM_PROTOCOL_VERSION = 1700
SEGWIT_ACTIVATION_VERSION = 17
BLOCK_MAX_SIZE = 1000000
BLOCK_MAX_WEIGHT = 4000000
```

Could you or anyone try to help please?!

Thank you,

**Comment by farsider350** [comment]
The problem I believe has been resolved here but it is not maintained what so ever.
https://github.com/farsider350/p2pool-1
