### ISSUE TITLE
p2pool - not support bitcoin daemon v 0.16.2

### ISSUE THREAD

**Issue by earthGavinLee** [p2pool/p2pool#397]
2018-08-24 07:55:51.423002 p2pool (version 17.0-12-gfa3162f)
2018-08-24 07:55:51.423065 
2018-08-24 07:55:51.423104 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username 'bitcoinrpc'...
2018-08-24 07:55:51.446563     ...success!
2018-08-24 07:55:51.446628     Current block hash: 1971f4c3cae0590bc4ab50838abf4475e80d6a82081551
2018-08-24 07:55:51.446656     Current block height: 538173
2018-08-24 07:55:51.446677 
2018-08-24 07:55:51.446703 Testing bitcoind P2P connection to '127.0.0.1:8333'...
2018-08-24 07:55:51.448075     ...success!
2018-08-24 07:55:51.448133 
2018-08-24 07:55:51.448170 Determining payout address...
2018-08-24 07:55:51.448232     Loaded cached address: 3LRnLxuMaamK49sWSychidDaQGZfpHK84B...
2018-08-24 07:55:51.452804 > Fatal error:
2018-08-24 07:55:51.452857 > Traceback (most recent call last):
2018-08-24 07:55:51.452878 >   File "/lib/python2.7/site-packages/twisted/internet/defer.py", line 488, in _startRunCallbacks
2018-08-24 07:55:51.452896 >     self._runCallbacks()
2018-08-24 07:55:51.452912 >   File "/lib/python2.7/site-packages/twisted/internet/defer.py", line 575, in _runCallbacks
2018-08-24 07:55:51.452929 >     current.result = callback(current.result, *args, **kw)
2018-08-24 07:55:51.452944 >   File "/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in gotResult
2018-08-24 07:55:51.452963 >     _inlineCallbacks(r, g, deferred)
2018-08-24 07:55:51.452978 >   File "/lib/python2.7/site-packages/twisted/internet/defer.py", line 1070, in _inlineCallbacks
2018-08-24 07:55:51.452994 >     result = g.send(result)
2018-08-24 07:55:51.453008 > --- <exception caught here> ---
2018-08-24 07:55:51.453022 >   File "/mnt/Pool/p2pool/p2pool/main.py", line 145, in main
2018-08-24 07:55:51.453036 >     my_pubkey_hash = bitcoin_data.address_to_pubkey_hash(address, net.PARENT)
2018-08-24 07:55:51.453061 >   File "/mnt/Pool/p2pool/p2pool/bitcoin/data.py", line 324, in address_to_pubkey_hash
2018-08-24 07:55:51.453078 >     raise ValueError('address not for this net!')
2018-08-24 07:55:51.453092 > exceptions.ValueError: address not for this net!

**Comment by farsider350** [comment]
This issue has already been covered. Generate a legacy address and use that.

**Comment by earthGavinLee** [comment]
./bitcoin-cli getnewaddress "" legacy
still issue

**Comment by LavishhVisions** [comment]
Im having the same issue, i dont know how to fix can you please help me

**Comment by farsider350** [comment]
Go to Core wallet Console and type 
getnewaddress "" legacy
copy the new address into p2pool/data/bitcoin/cached_payout_address

**Comment by LavishhVisions** [comment]
Thanks man
