### ISSUE TITLE
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares

### ISSUE THREAD

**Issue by faca5** [p2pool/p2pool#409]
Unhandled Error
Traceback (most recent call last):
  File "/root/p2pool/p2pool/main.py", line 675, in run
    reactor.run()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
    self.mainLoop()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 1270, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib64/python2.7/site-packages/twisted/internet/base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/root/p2pool/p2pool/bitcoin/stratum.py", line 38, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/root/p2pool/p2pool/bitcoin/worker_interface.py", line 129, in get_work
    x, handler = self._inner.get_work(*args)
  File "/root/p2pool/p2pool/work.py", line 245, in get_work
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares

**Comment by farsider350** [comment]
Give it time to download the shares.
