### ISSUE TITLE
Failing to start due to hash length (Bitcoin RPC issue)

### ISSUE THREAD

**Issue by arch-linux** [p2pool/p2pool#428]
My p2pool server fails to start with an issue based on the following issue ticket.
[#419](https://github.com/p2pool/p2pool/issues/419)

As instructed, I generated a legacy address using the bitcoin core from [#397](https://github.com/p2pool/p2pool/issues/397) inserted it in.

Following that, I removed the statement dealing with the following problem.
`if not res['isvalid'] or not res['ismine']:`

After checking and verifying my address is correct, and regenerating them using the previous command I am failing to start the server based on this issue

```
Error:
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/pool/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/pool/p2pool/p2pool/util/deferral.py", line 172, in __call__
    value = yield self.func(key)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/pool/p2pool/p2pool/bitcoin/height_tracker.py", line 104, in height_cacher
    x = yield bitcoind.rpc_getblockheader('%x' % (block_hash,))
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/pool/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: -8 hash must be of length 64 (not 46, for '1bbf433b0b4141987e385d8ffed52960b76f0a57b76f33')
```

Im clueless as to what's happening here, i know for a fact that my address is correct, I have verified that the above address is correct. and it is in p2pool/data/bitcoin/cached_payout_address

Thanks for any help

**Comment by forrestv** [comment]
Can you try changing the "%x" referenced in the traceback
(height_tracker.py, line 104) to "%064x"?

The block hash wasn't being zero-padded; maybe previous versions of Bitcoin
accepted that, but now it's more strict.

**Comment by farsider350** [comment]
Also a simple delete of the data folder before startup will work.

**Comment by arch-linux** [comment]
@farsider350
@forrestv

Thank you, I was able to get passed this issue. 

To recap, to fix the issue I deleted the data directory, changed the operand from %x to %064x and injected my generated legacy address into the cached_payout_address file.
