### ISSUE TITLE
Datachunker : wants = receiver.send(buf.get(wants)) --- Issue on connection 

### ISSUE THREAD

**Issue by arch-linux** [p2pool/p2pool#429]
Hello Again!

New problem new issue request, I appreciate all of the help.
My server is currently using the following from #428. 

Upon almost every connection, I receive an error in the console as following.

```

Traceback (most recent call last):
Failure: twisted.internet.error.ConnectionAborted: Connection was aborted locally, using.

2019-08-12 22:57:05.779511 Peer **IP-REMOVED** says protocol version is 3301, client version 15.0-134-gfea30fd-dirty
2019-08-12 22:57:05.779793 Outgoing connection to peer **IP-REMOVED** established. p2pool version: 3301 '15.0-134-gfea30fd-dirty'
2019-08-12 22:57:06.022220 Peer **IP-REMOVED** says protocol version is 3301, client version 16.0-156-gf63da63-dirty
2019-08-12 22:57:06.022481 Outgoing connection to peer **IP-REMOVED** established. p2pool version: 3301 '16.0-156-gf63da63-dirty'
2019-08-12 22:57:06.080697 Sending 1 shares to **IP-REMOVED**
2019-08-12 22:57:06.465932 RECV sharereply 64d1888d03490fc5184e38bf5781696acfef9378eee89958b591e6161b057ae9000122fd0404fe0000402098688cb8c720afbbf506eed77cc167089d0c6cdb51e51600000000000000000041ee515d39301c170b16f2cb4ac362fdd266c57ab3ef15662f...
Error handling message: (see RECV line)
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/pool/p2pool/p2pool/p2p.py", line 173, in new_dataReceived
    old_dataReceived(data)
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 27, in dataReceived
    self.dataReceived2(data)
  File "/home/pool/p2pool/p2pool/util/datachunker.py", line 40, in _DataChunker
    wants = receiver.send(buf.get(wants))
--- <exception caught here> ---
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 57, in dataReceiver
    self.packetReceived(command, type_.unpack(payload, self.ignore_trailing_payload))
  File "/home/pool/p2pool/p2pool/p2p.py", line 91, in packetReceived
    p2protocol.Protocol.packetReceived(self, command, payload2)
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 71, in packetReceived
    handler(**payload2)
  File "/home/pool/p2pool/p2pool/p2p.py", line 410, in handle_sharereply
    res = [p2pool_data.load_share(share, self.node.net, self.addr) for share in shares if share['type'] >= p2pool_data.Share.VERSION]
  File "/home/pool/p2pool/p2pool/data.py", line 60, in load_share
    raise ValueError('unknown share type: %r' % (share['type'],))
exceptions.ValueError: unknown share type: 34

2019-08-12 22:57:06.468536 Lost peer **IP-REMOVED** - Connection was aborted locally, using.
in handle_share_hashes:


Error handling message: (see RECV line)
Traceback (most recent call last):
  File "/usr/local/lib/pypy2.7/dist-packages/Twisted-15.4.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 215, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/pool/p2pool/p2pool/p2p.py", line 173, in new_dataReceived
    old_dataReceived(data)
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 27, in dataReceived
    self.dataReceived2(data)
  File "/home/pool/p2pool/p2pool/util/datachunker.py", line 40, in _DataChunker
    wants = receiver.send(buf.get(wants))
--- <exception caught here> ---
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 57, in dataReceiver
    self.packetReceived(command, type_.unpack(payload, self.ignore_trailing_payload))
  File "/home/pool/p2pool/p2pool/p2p.py", line 91, in packetReceived
    p2protocol.Protocol.packetReceived(self, command, payload2)
  File "/home/pool/p2pool/p2pool/util/p2protocol.py", line 71, in packetReceived
    handler(**payload2)
  File "/home/pool/p2pool/p2pool/p2p.py", line 410, in handle_sharereply
    res = [p2pool_data.load_share(share, self.node.net, self.addr) for share in shares if share['type'] >= p2pool_data.Share.VERSION]
  File "/home/pool/p2pool/p2pool/data.py", line 60, in load_share
    raise ValueError('unknown share type: %r' % (share['type'],))
exceptions.ValueError: unknown share type: 34


```

Again, i'm scratching my head at this one; 
I have verified that my Bitcoin Core is up to date on the blockchain and as mentioned earlier my legacy address is posted in the cached_address file.
This lends me to believe the problem is originating from a different source.

Thanks for the help again!

**Comment by rskiba** [comment]
I am experiencing exactly the same problem on Litecoin in P2Pool, error ending as exceptions.ValueError: unknown share type: 34.
Has anyone been able to resolve this?

**Comment by farsider350** [comment]
The best option is to use p2pool referred to in #411 
It has been updated for the newer Bitcoin/Litecoin clients.

**Comment by rskiba** [comment]
Thankyou for the help, much appreciated.  All working now. Thanks again.
