### ISSUE TITLE
Error while checking Bitcoin connection

### ISSUE THREAD

**Issue by otoolebe** [p2pool/p2pool#434]
Getting the following error while starting up p2pool in Ubuntu18 with bitcoind running. 

Error while checking Bitcoin connection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/lib/python2.7/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "~/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "~/p2pool/p2pool/bitcoin/helper.py", line 26, in check
    softforks_supported = set(item['id'] for item in blockchaininfo.get('softforks', []))
  File "~/p2pool/p2pool/bitcoin/helper.py", line 26, in <genexpr>
    softforks_supported = set(item['id'] for item in blockchaininfo.get('softforks', []))
exceptions.TypeError: string indices must be integers

**Comment by wayne8080** [comment]
Hi！
I had a same error.
Have you found the problem？

**Comment by farsider350** [comment]
The error your facing is due to p2pool not looking for the correct softforks that Bitcoin now has active on the network.

An up to date version of p2pool that works with the latest Bitcoin Core can be found here. https://github.com/jtoomim/p2pool
