### ISSUE TITLE
Coin daemon too old! Upgrade!

### ISSUE THREAD

**Issue by CocolinoFan** [p2pool/p2pool#439]
Any ideas what could be causing this? 

```
2022-11-04 21:40:04.297339 p2pool (version 17.0-14-g53c438b)
2022-11-04 21:40:04.297399
2022-11-04 21:40:04.297440 Testing bitcoind RPC connection to 'http://127.0.0.1:8332/' with username ''...
Error while checking Bitcoin connection:
Traceback (most recent call last):
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "/home/cocolino/SSD/Programs/p2pool/p2pool/util/deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/cocolino/SSD/Programs/p2pool/p2pool/bitcoin/helper.py", line 13, in check
    if not (yield net.PARENT.RPC_CHECK(bitcoind)):
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/cocolino/SSD/Programs/p2pool/p2pool/bitcoin/networks/bitcoin.py", line 15, in <lambda>
    (yield helper.check_genesis_block(bitcoind, '000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f')) and
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/cocolino/SSD/Programs/p2pool/p2pool/bitcoin/helper.py", line 112, in check_genesis_block
    yield bitcoind.rpc_getblock(genesis_block_hash)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/home/cocolino/SSD/Programs/p2pool/p2pool/util/jsonrpc.py", line 133, in _http_do
    raise Error_for_code(resp['error']['code'])(resp['error']['message'], resp['error'].get('data', None))
p2pool.util.jsonrpc.NarrowError: <NarrowError instance at 0x7f0008d03c80 with str error:
 Traceback (most recent call last):
  File "/home/cocolino/.pyenv/versions/2.7.13/lib/python2.7/site-packages/twisted/python/reflect.py", line 448, in safe_str
    return str(o)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 20: ordinal not in range(128)
>
2022-11-04 21:40:07.380409 Coin daemon too old! Upgrade!
2022-11-04 21:40:08.391999 Coin daemon too old! Upgrade!
2022-11-04 21:40:09.397326 Coin daemon too old! Upgrade!
2022-11-04 21:40:10.426351 Coin daemon too old! Upgrade!

```

EDIT: I am running bitcoin core 23.0.0 downloaded from the official bitcoin.org. I have a full copy of the blockchain and I have `txindex=1` in the config.

**Comment by CocolinoFan** [comment]
I should also add that I am using `pyenv` locally (inside the p2pool directory) to run the program on python 2.7.13

**Comment by CocolinoFan** [comment]
Ok forget about that long error list. My main issue is that I get `Coin daemon too old! Upgrade!` and I have no clue what could be causing this. 
Any help would be greatly appreciated.

**Comment by farsider350** [comment]
#411
